### ISSUE TITLE
Not able to fetch location on Mobile Devices

### ISSUE THREAD

**Issue by ashish333mishra** [ashish333mishra/Weather-App-JS#7]
You can check this issue by visiting.

https://ashish333mishra.github.io/Weather-App-JS/

**Comment by vikasganiga05** [comment]
> You can check this issue by visiting.
> 
> https://ashish333mishra.github.io/Weather-App-JS/

The user needs to manually on the Location of his Mobile.

**Comment by ashish333mishra** [comment]
Yes vikas you are right!
Thanks 😊
